extends: eslint-config-airbnb
env:
  browser: true
  node: true
settings:
  import/resolver: webpack
rules:
  react/prop-types: "off"
  react/jsx-filename-extension: "off"
  react/react-in-jsx-scope: "off"
  react/no-unknown-property: "off"
